version: '3.3'

volumes:
  foodgram_data:
  foodgram_static:
  foodgram_media:

services:

  foodgram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - foodgram_data:/var/lib/postgresql/data
  
  backend:
    image: artyomkoshurin/foodgram_backend
    env_file: .env
    volumes:
      - foodgram_static:/app/static/
      - foodgram_media:/app/media/
    depends_on:
      - foodgram_db

  frontend:
    image: artyomkoshurin/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - 8000:80
    volumes:
      - ./nginx_production.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - foodgram_data:/var/html/static/
      - foodgram_static:/var/html/media/
    depends_on:
      - backend
      - frontend