# Generated by Django 4.2.5 on 2023-10-25 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_ingredientsforrecipe_ingredient_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="is_favourite",
            new_name="is_favourited",
        ),
    ]
