# Generated by Django 4.2.5 on 2023-10-31 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_recipe_is_in_shopping_cart_shoppingcart_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="tag",
            new_name="tags",
        ),
    ]
