# Generated by Django 4.2.5 on 2023-11-02 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_rename_tag_recipe_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="measure_unit",
            new_name="measurement_unit",
        ),
    ]
