# Generated by Django 4.2.5 on 2023-11-06 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_rename_measure_unit_ingredient_measurement_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
    ]
