# Generated by Django 4.2.5 on 2023-11-09 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_rename_description_recipe_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredientsforrecipe",
            old_name="portion",
            new_name="amount",
        ),
    ]
